name: WakaTime status update

on:
  push:
    branches: [master]
  schedule:
    - cron: "1 0 * * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update WakaTime Stat
        uses: yashksaini-coder/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "main"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          STATS_RANGE: "last_7_days"
