name: Sponsors Activity
on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push: { branches: ["master", "main", "metrics"] }
jobs:
  # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
  language-activity-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
            filename: assets/metrics.plugin.sponsors.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_sponsors: yes
            plugin_sponsors_sections: goal, list
            plugin_sponsors_past: yes
            plugin_sponsors_title: "Sponsor Me"
            plugin_sponsors_size: 12